---
# tasks file for vpn

- name: Create the /usr/local/etc/openvpn/ directory
  file: path=/usr/local/etc/openvpn state=directory mode=0700
  tags: make_usr_local_etc

- name: Creating OVPN file
  template:
    src:          client.ovpn.j2
    dest:         "/usr/local/etc/openvpn/{{ config_prefix }}.ovpn"
    owner:        root
    group:        root
    mode:         '0600'
